#!/usr/bin/env bash

red=$'\e[1;31m'
nocolor=$'\e[0m'

# Assign stdin to keyboard
exec < /dev/tty

# Get any added or modified .go files from git. Proceed commit if there's none.
files=$(git diff --cached --name-only | grep '\.go$')
[ -z "$files" ] && exit 0

# Run gometalinter. Proceed commit if it doesn't raise any issues.
issues=$(gometalinter $files)
[ -z "$issues" ] && exit 0

printf "${red}gometalinter raised issues:${nocolor}\n$issues\n"
read -p "${red}Would you like to proceed committing? (y/n)${nocolor} " proceed && [ "$proceed" == "y" ] && exit 0

printf "${red}Aborting commit${nocolor}\n"; exit 1
